import { axios } from '@/utils/request'

/**
 * 查询设备信息
 *
 * @author Chris
 */
export function DeviceInfoPage (parameter) {
  return axios({
    url: '/DeviceInfo/page',
    method: 'get',
    params: parameter
  })
}

/**
 * 设备信息列表
 *
 * @author Chris
 */
export function DeviceInfoList (parameter) {
  return axios({
    url: '/DeviceInfo/list',
    method: 'get',
    params: parameter
  })
}

/**
 * 添加设备信息
 *
 * @author Chris
 */
export function DeviceInfoAdd (parameter) {
  return axios({
    url: '/DeviceInfo/add',
    method: 'post',
    data: parameter
  })
}

/**
 * 编辑设备信息
 *
 * @author Chris
 */
export function DeviceInfoEdit (parameter) {
  return axios({
    url: '/DeviceInfo/edit',
    method: 'post',
    data: parameter
  })
}

/**
 * 删除设备信息
 *
 * @author Chris
 */
export function DeviceInfoDelete (parameter) {
  return axios({
    url: '/DeviceInfo/delete',
    method: 'post',
    data: parameter
  })
}

/**
 * 导出设备信息
 *
 * @author Chris
 * @date 2021/7/30 01:00
 */
export function DeviceInfoExport (parameter) {
  return axios({
    url: '/DeviceInfo/export',
    method: 'get',
    data: parameter,
    responseType: 'blob'
  })
}

/*
 * 转移设备
 * @author Chris
 * @date 2021/8/9
 */
export function DeviceInfoTransfer (parameter) {
  return axios({
    url: '/DeviceInfo/transfer',
    method: 'post',
    data: parameter
  })
}

/**
 * 查询设备
 */
export function DeviceInfoFromIDs (parameter) {
  return axios({
    url: '/DeviceInfo/getfromIds',
    method: 'post',
    data: parameter
  })
}

/**
 * 批量更新设备
 */
export function DeviceInfoLotUpdate (parameter) {
  return axios({
    url: '/DeviceInfo/lotupdate',
    method: 'post',
    data: parameter
  })
}

export function GetDeviceOTree (parameter) {
  // return axios({
  //   url: '/DeviceInfo/dtree',
  //   method: 'get',
  //   params: parameter,
  // })
  return new Promise((resolve, reject) => {
    const abc = {
      'success': true,
      'code': 200,
      'message': '请求成功',
      'data': [
        {
          'all_DeviceCount': 4,
          'cur_DeviceCount': 1,
          'id': 174827013677125,
          'parentId': 0,
          'title': '之旺[1/4]',
          'value': '174827013677125',
          'weight': 100,
          'pids': '[0],',
          'children': [
            {
              'all_DeviceCount': 3,
              'cur_DeviceCount': 1,
              'id': 174827366686789,
              'parentId': 174827013677125,
              'title': '王伟测试账号[1/3]',
              'value': '174827366686789',
              'weight': 100,
              'pids': '[0],[174827013677125],',
              'children': [
                {
                  'all_DeviceCount': 2,
                  'cur_DeviceCount': 2,
                  'id': 186755437695045,
                  'parentId': 174827366686789,
                  'title': '111[2/2]',
                  'value': '186755437695045',
                  'weight': 100,
                  'pids': '[0],[174827013677125],[174827366686789],',
                  'children': [
                    {
                      'all_DeviceCount': 0,
                      'cur_DeviceCount': 0,
                      'id': 200153472262213,
                      'parentId': 186755437695045,
                      'title': 'sssssss[0/0]',
                      'value': '200153472262213',
                      'weight': 100,
                      'pids': '[0],[174827013677125],[174827366686789],[186755437695045],',
                      'children': [],
                      'pid': 186755437695045
                    },
                    {
                      'all_DeviceCount': 0,
                      'cur_DeviceCount': 0,
                      'id': 196964932288581,
                      'parentId': 186755437695045,
                      'title': '2222[0/0]',
                      'value': '196964932288581',
                      'weight': 100,
                      'pids': '[0],[174827013677125],[174827366686789],[186755437695045],',
                      'children': [],
                      'pid': 186755437695045
                    },
                    {
                      'all_DeviceCount': 0,
                      'cur_DeviceCount': 0,
                      'id': 200154121171013,
                      'parentId': 186755437695045,
                      'title': 'ssssss[0/0]',
                      'value': '200154121171013',
                      'weight': 100,
                      'pids': '[0],[174827013677125],[174827366686789],[186755437695045],',
                      'children': [],
                      'pid': 186755437695045
                    }
                  ],
                  'pid': 174827366686789
                },
                {
                  'all_DeviceCount': 0,
                  'cur_DeviceCount': 0,
                  'id': 200658405277765,
                  'parentId': 174827366686789,
                  'title': '11111[0/0]',
                  'value': '200658405277765',
                  'weight': 100,
                  'pids': '[0],[174827013677125],[174827366686789],',
                  'children': [],
                  'pid': 174827366686789
                }
              ],
              'pid': 174827013677125
            },
            {
              'all_DeviceCount': 0,
              'cur_DeviceCount': 0,
              'id': 174829383766085,
              'parentId': 174827013677125,
              'title': 'A公司[0/0]',
              'value': '174829383766085',
              'weight': 100,
              'pids': '[0],[174827013677125],',
              'children': [
                {
                  'all_DeviceCount': 0,
                  'cur_DeviceCount': 0,
                  'id': 196888284803141,
                  'parentId': 174829383766085,
                  'title': '3333[0/0]',
                  'value': '196888284803141',
                  'weight': 100,
                  'pids': '[0],[174827013677125],[174829383766085],',
                  'children': [],
                  'pid': 174829383766085
                }
              ],
              'pid': 174827013677125
            }
          ],
          'pid': 0
        },
        {
          'all_DeviceCount': 0,
          'cur_DeviceCount': 0,
          'id': 198067753734213,
          'parentId': 0,
          'title': '444[0/0]',
          'value': '198067753734213',
          'weight': 100,
          'pids': '[0],',
          'children': [
            {
              'all_DeviceCount': 0,
              'cur_DeviceCount': 0,
              'id': 198237207265349,
              'parentId': 198067753734213,
              'title': '6666[0/0]',
              'value': '198237207265349',
              'weight': 100,
              'pids': '[0],[198067753734213],',
              'children': [],
              'pid': 198067753734213
            },
            {
              'all_DeviceCount': 0,
              'cur_DeviceCount': 0,
              'id': 198249705594949,
              'parentId': 198067753734213,
              'title': '7777[0/0]',
              'value': '198249705594949',
              'weight': 100,
              'pids': '[0],[198067753734213],',
              'children': [],
              'pid': 198067753734213
            }
          ],
          'pid': 0
        },
        {
          'all_DeviceCount': 0,
          'cur_DeviceCount': 0,
          'id': 198054597918789,
          'parentId': 0,
          'title': '333[0/0]',
          'value': '198054597918789',
          'weight': 100,
          'pids': '[0],',
          'children': [],
          'pid': 0
        }
      ],
      'extras': null,
      'timestamp': 1631628675370
    }
    resolve(abc)
  })
}

export function GetMapDeviceList (parameter) {
  return new Promise((resolve, reject) => {
    const abc = {
      'success': true,
      'code': 200,
      'message': '请求成功',
      'data': {
        'pageNo': 1,
        'pageSize': 20,
        'totalPage': 3,
        'totalRows': 47,
        'rows': [
          {
            'deviceName': '58213800236',
            'deviceNo': '58213800236',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.58,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:39',
            'lastLocDtime': '2021-10-04 07:37:39',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843566,
            'cur_log': 116.721583,
            'cur_attitude': 13,
            'cur_speed': 0,
            'cur_direction': 334,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800236',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721583,
                'alertPosition_y': 39.843566,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800236',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721583,
                'alertPosition_y': 39.843566,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800237',
            'deviceNo': '58213800237',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.27,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:19',
            'lastLocDtime': '2021-10-04 07:37:19',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.8436,
            'cur_log': 116.721733,
            'cur_attitude': 24,
            'cur_speed': 0,
            'cur_direction': 353,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790530',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800237',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721733,
                'alertPosition_y': 39.8436,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800237',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721733,
                'alertPosition_y': 39.8436,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800239',
            'deviceNo': '58213800239',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.04,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:39',
            'lastLocDtime': '2021-10-04 07:37:39',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843633,
            'cur_log': 116.721633,
            'cur_attitude': 19,
            'cur_speed': 0,
            'cur_direction': 319,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800239',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721633,
                'alertPosition_y': 39.843633,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800239',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721633,
                'alertPosition_y': 39.843633,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800242',
            'deviceNo': '58213800242',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:33',
            'lastLocDtime': '2021-10-04 07:37:33',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843633,
            'cur_log': 116.721633,
            'cur_attitude': 19,
            'cur_speed': 0,
            'cur_direction': 327,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800242',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721633,
                'alertPosition_y': 39.843633,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800242',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721633,
                'alertPosition_y': 39.843633,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800246',
            'deviceNo': '58213800246',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.27,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:36:49',
            'lastLocDtime': '2021-10-04 07:36:49',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843733,
            'cur_log': 116.721933,
            'cur_attitude': 21,
            'cur_speed': 0,
            'cur_direction': 0,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790530',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800246',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721933,
                'alertPosition_y': 39.843733,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800246',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721933,
                'alertPosition_y': 39.843733,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800248',
            'deviceNo': '58213800248',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.63,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:38:57',
            'lastLocDtime': '2021-10-04 07:38:57',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843483,
            'cur_log': 116.721766,
            'cur_attitude': 23,
            'cur_speed': 0,
            'cur_direction': 0,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800248',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721766,
                'alertPosition_y': 39.843483,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800248',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721766,
                'alertPosition_y': 39.843483,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800250',
            'deviceNo': '58213800250',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.4,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:25',
            'lastLocDtime': '2021-10-04 07:37:25',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843533,
            'cur_log': 116.7218,
            'cur_attitude': 19,
            'cur_speed': 0,
            'cur_direction': 0,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800250',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7218,
                'alertPosition_y': 39.843533,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800250',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7218,
                'alertPosition_y': 39.843533,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800251',
            'deviceNo': '58213800251',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.4,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:38:38',
            'lastLocDtime': '2021-10-04 07:38:38',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.8436,
            'cur_log': 116.7216,
            'cur_attitude': 36,
            'cur_speed': 0,
            'cur_direction': 326,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790530',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800251',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7216,
                'alertPosition_y': 39.8436,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800251',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7216,
                'alertPosition_y': 39.8436,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800259',
            'deviceNo': '58213800259',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.04,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:38:35',
            'lastLocDtime': '2021-10-04 07:38:35',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843583,
            'cur_log': 116.721683,
            'cur_attitude': 33,
            'cur_speed': 0,
            'cur_direction': 0,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800259',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721683,
                'alertPosition_y': 39.843583,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800259',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721683,
                'alertPosition_y': 39.843583,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800262',
            'deviceNo': '58213800262',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 62.91,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:33',
            'lastLocDtime': '2021-10-04 07:37:33',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.84365,
            'cur_log': 116.721666,
            'cur_attitude': 23,
            'cur_speed': 0,
            'cur_direction': 58,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800262',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721666,
                'alertPosition_y': 39.84365,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800262',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721666,
                'alertPosition_y': 39.84365,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800264',
            'deviceNo': '58213800264',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.27,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:31:04',
            'lastLocDtime': '2021-10-04 07:31:04',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.8437,
            'cur_log': 116.721633,
            'cur_attitude': 12,
            'cur_speed': 0,
            'cur_direction': 0,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800264',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721633,
                'alertPosition_y': 39.8437,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800264',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721633,
                'alertPosition_y': 39.8437,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800266',
            'deviceNo': '58213800266',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 62.86,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:34',
            'lastLocDtime': '2021-10-04 07:37:34',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.84365,
            'cur_log': 116.721633,
            'cur_attitude': 24,
            'cur_speed': 0,
            'cur_direction': 322,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800266',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721633,
                'alertPosition_y': 39.84365,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800266',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721633,
                'alertPosition_y': 39.84365,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800267',
            'deviceNo': '58213800267',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.13,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:38:32',
            'lastLocDtime': '2021-10-04 07:38:32',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843666,
            'cur_log': 116.721683,
            'cur_attitude': 27,
            'cur_speed': 0,
            'cur_direction': 0,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800267',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721683,
                'alertPosition_y': 39.843666,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800267',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721683,
                'alertPosition_y': 39.843666,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800271',
            'deviceNo': '58213800271',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.09,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:36:49',
            'lastLocDtime': '2021-10-04 07:36:49',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.8434,
            'cur_log': 116.721766,
            'cur_attitude': 18,
            'cur_speed': 0,
            'cur_direction': 336,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800271',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721766,
                'alertPosition_y': 39.8434,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800271',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721766,
                'alertPosition_y': 39.8434,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800272',
            'deviceNo': '58213800272',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 62.86,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:34',
            'lastLocDtime': '2021-10-04 07:37:34',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843616,
            'cur_log': 116.721616,
            'cur_attitude': 12,
            'cur_speed': 0,
            'cur_direction': 347,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790530',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800272',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721616,
                'alertPosition_y': 39.843616,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800272',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721616,
                'alertPosition_y': 39.843616,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800277',
            'deviceNo': '58213800277',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.36,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:37:34',
            'lastLocDtime': '2021-10-04 07:37:34',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.84365,
            'cur_log': 116.7216,
            'cur_attitude': 12,
            'cur_speed': 0,
            'cur_direction': 333,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790530',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800277',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7216,
                'alertPosition_y': 39.84365,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800277',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7216,
                'alertPosition_y': 39.84365,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800278',
            'deviceNo': '58213800278',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.27,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:38:00',
            'lastLocDtime': '2021-10-04 07:38:00',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843166,
            'cur_log': 116.722,
            'cur_attitude': 11,
            'cur_speed': 0,
            'cur_direction': 0,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800278',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.722,
                'alertPosition_y': 39.843166,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800278',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.722,
                'alertPosition_y': 39.843166,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800280',
            'deviceNo': '58213800280',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:38:41',
            'lastLocDtime': '2021-10-04 07:38:41',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843633,
            'cur_log': 116.721683,
            'cur_attitude': 25,
            'cur_speed': 0,
            'cur_direction': 32,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790530',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800280',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721683,
                'alertPosition_y': 39.843633,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800280',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.721683,
                'alertPosition_y': 39.843633,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800282',
            'deviceNo': '58213800282',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 64.89,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:38:39',
            'lastLocDtime': '2021-10-04 07:38:39',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843733,
            'cur_log': 116.7216,
            'cur_attitude': 5,
            'cur_speed': 0,
            'cur_direction': 0,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800282',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7216,
                'alertPosition_y': 39.843733,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800282',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7216,
                'alertPosition_y': 39.843733,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          },
          {
            'deviceName': '58213800284',
            'deviceNo': '58213800284',
            'device_time': null,
            'fortifiedState': '0',
            'batteryVoltage': 63.13,
            'on_off_state': '1',
            'locType': '3',
            'lastComDtime': '2021-10-04 07:36:50',
            'lastLocDtime': '2021-10-04 07:36:50',
            'gps_grade': '',
            'gms_grade': '',
            'cur_lat': 39.843583,
            'cur_log': 116.7218,
            'cur_attitude': 24,
            'cur_speed': 0,
            'cur_direction': 10,
            'cur_map_fence_id': 0,
            'cur_waringmark': '0',
            'cur_status': '790528',
            'cur_gps_miles': 0,
            'cur_day_miles': 0,
            'cur_soc': 0,
            'acc_on': '',
            'deviceStatus': '1',
            'alarmList': [
              {
                'deviceNo': '58213800284',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7218,
                'alertPosition_y': 39.843583,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213800284',
                'alertDtime': '2021-10-07 17:43:26',
                'alertDate': '2021-10-07',
                'alertPosition_x': 116.7218,
                'alertPosition_y': 39.843583,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ]
          }
        ]
      },
      'extras': null,
      'timestamp': 1633599806296
    }
    resolve(abc)
  })
}

export function GetDeviceLocList (parameter) {
  return new Promise((resolve, reject) => {
    const abc = {
      'success': true,
      'code': 200,
      'message': '请求成功',
      'data': {
        'pageNo': 1,
        'pageSize': 20,
        'totalPage': 1,
        'totalRows': 2,
        'rows': [
          {
            'mobile_no': '58213700075',
            'batteryVoltage': 70.74,
            'latitude': 120.49766,
            'longitude': 31.696866,
            'speed': 0,
            'device_time': '2021/10/2 4:41:44',
            'warning_mark': '0',
            'status': 11000001010000000000,
            'altitude': 2,
            'alarmList': [
              {
                'deviceNo': '58213700075',
                'alertDtime': '2021-10-09 16:02:54',
                'alertDate': '2021-10-09',
                'alertPosition_x': 120.498866,
                'alertPosition_y': 31.696866,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213700075',
                'alertDtime': '2021-10-09 16:02:54',
                'alertDate': '2021-10-09',
                'alertPosition_x': 120.498866,
                'alertPosition_y': 31.696866,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ],
            'staytime': '1天8小时40分钟0秒',
            'mileage': 3
          },
          {
            'mobile_no': '58213700075',
            'batteryVoltage': 70.65,
            'latitude': 120.4989,
            'longitude': 31.69735,
            'speed': 0,
            'device_time': '2021/10/5 16:00:30',
            'warning_mark': '0',
            'status': 11000001010000000000,
            'altitude': 0,
            'alarmList': [
              {
                'deviceNo': '58213700075',
                'alertDtime': '2021-10-09 16:02:54',
                'alertDate': '2021-10-09',
                'alertPosition_x': 31.69705,
                'alertPosition_y': 120.4989,
                'alertPosition': null,
                'alertType': '1',
                'alertInfo': '超速报警',
                'curSpeed': null,
                'alterStatus': '1',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              },
              {
                'deviceNo': '58213700075',
                'alertDtime': '2021-10-09 16:02:54',
                'alertDate': '2021-10-09',
                'alertPosition_x': 31.69705,
                'alertPosition_y': 120.4989,
                'alertPosition': null,
                'alertType': '0',
                'alertInfo': '紧急报警',
                'curSpeed': null,
                'alterStatus': '2',
                'isHandled': null,
                'handleInfo': null,
                'tenantId': null,
                'id': 0,
                'createdTime': null,
                'updatedTime': null,
                'createdUserId': null,
                'createdUserName': null,
                'updatedUserId': null,
                'updatedUserName': null,
                'isDeleted': false
              }
            ],
            'staytime': null,
            'mileage': 10
          }
        ]
      },
      'extras': null,
      'timestamp': 1633766575903
    }
    resolve(abc)
  })
}
