/*
 * @Author: ulongx
 * @Date: 2021-09-11 22:23:24
 * @LastEditors: ulongx
 * @LastEditTime: 2021-09-11 22:24:36
 * @FilePath: /frontend/src/utils/dictDataTree.js
 */
const dictData = {
  'success': true,
  'code': 200,
  'message': '请求成功',
  'data': {
    'id': 142307070910551,
    'account': 'superAdmin',
    'nickName': 'superAdmin',
    'name': '超级管理员',
    'avatar': null,
    'birthday': '1986-07-18 16:00:00',
    'sex': 1,
    'email': '1@aibowang.com',
    'phone': '13000000000',
    'tel': null,
    'adminType': 1,
    'lastLoginIp': '0.0.0.1',
    'lastLoginTime': '2021-09-11 21:20:11',
    'lastLoginAddress': null,
    'lastLoginBrowser': 'Chrome93',
    'lastLoginOs': 'Windows10',
    'loginEmpInfo': {
      'jobNum': 'D1001',
      'orgId': '174827013677125',
      'orgName': '爱博旺（江苏）新能源有限公司',
      'extOrgPos': [],
      'positions': [
        {
          'posId': 142307070910547,
          'posCode': 'zjl',
          'posName': '总经理'
        },
        {
          'posId': 142307070910548,
          'posCode': 'fzjl',
          'posName': '副总经理'
        }
      ]
    },
    'apps': [
      {
        'id': 0,
        'name': '业务应用',
        'code': 'busiapp',
        'active': 'N',
        'sort': 0
      },
      {
        'id': 0,
        'name': '平台管理',
        'code': 'system',
        'active': 'Y',
        'sort': 0
      },
      {
        'id': 0,
        'name': '设备租赁',
        'code': 'rent',
        'active': 'N',
        'sort': 0
      },
      {
        'id': 0,
        'name': '运营管理',
        'code': 'platform',
        'active': 'N',
        'sort': 0
      },
      {
        'id': 0,
        'name': '系统管理',
        'code': 'manage',
        'active': 'N',
        'sort': 0
      }
    ],
    'roles': [],
    'permissions': [
      'sysUser:page',
      'sysUser:edit',
      'sysUser:add',
      'sysUser:delete',
      'sysUser:detail',
      'sysUser:export',
      'sysUser:selector',
      'sysUser:grantRole',
      'sysUser:ownRole',
      'sysUser:grantData',
      'sysUser:ownData',
      'sysUser:updateInfo',
      'sysUser:updatePwd',
      'sysUser:changeStatus',
      'sysUser:updateAvatar',
      'sysUser:resetPwd',
      'sysOrg:page',
      'sysOrg:list',
      'sysOrg:add',
      'sysOrg:edit',
      'sysOrg:delete',
      'sysOrg:detail',
      'sysOrg:tree',
      'sysPos:page',
      'sysPos:list',
      'sysExLog:page',
      'sysExLog:delete',
      'sysPos:add',
      'sysPos:edit',
      'sysPos:delete',
      'sysPos:detail',
      'sysApp:page',
      'sysApp:list',
      'sysApp:add',
      'sysApp:edit',
      'sysApp:delete',
      'sysApp:detail',
      'sysApp:setAsDefault',
      'sysMenu:list',
      'sysMenu:add',
      'sysMenu:edit',
      'sysMenu:delete',
      'sysMenu:detail',
      'sysMenu:treeForGrant',
      'sysMenu:tree',
      'sysMenu:change',
      'sysRole:page',
      'sysRole:add',
      'sysRole:edit',
      'sysRole:delete',
      'sysRole:detail',
      'sysRole:dropDown',
      'sysRole:grantMenu',
      'sysRole:ownMenu',
      'sysRole:grantData',
      'sysRole:ownData',
      'sysConfig:page',
      'sysConfig:list',
      'sysConfig:add',
      'sysConfig:edit',
      'sysConfig:delete',
      'sysConfig:detail',
      'email:sendEmail',
      'email:sendEmailHtml',
      'sms:page',
      'sms:sendLoginMessage',
      'sms:validateMessage',
      'sysDictType:page',
      'sysDictType:list',
      'sysDictType:add',
      'sysDictType:delete',
      'sysDictType:edit',
      'sysDictType:detail',
      'sysDictType:dropDown',
      'sysDictType:changeStatus',
      'sysDictData:page',
      'sysDictData:list',
      'sysDictData:add',
      'sysDictData:delete',
      'sysDictData:edit',
      'sysDictData:detail',
      'sysDictData:changeStatus',
      'sysVisLog:page',
      'sysVisLog:delete',
      'sysOpLog:page',
      'sysOpLog:delete',
      'sysMachine:query',
      'sysOnlineUser:list',
      'sysOnlineUser:forceExist',
      'sysNotice:page',
      'sysNotice:add',
      'sysNotice:edit',
      'sysNotice:delete',
      'sysNotice:detail',
      'sysNotice:changeStatus',
      'sysNotice:received',
      'sysFileInfo:page',
      'sysFileInfo:list',
      'sysFileInfo:delete',
      'sysFileInfo:detail',
      'sysFileInfo:upload',
      'sysFileInfo:download',
      'sysFileInfo:preview',
      'sysTimers:page',
      'sysTimers:list',
      'sysTimers:detail',
      'sysTimers:add',
      'sysTimers:delete',
      'sysTimers:edit',
      'sysTimers:getActionClasses',
      'sysTimers:start',
      'sysTimers:stop',
      'sysFileInfo:uploadAvatar',
      'sysFileInfo:uploadDocument',
      'sysFileInfo:uploadShop',
      'DeviceInfo:page',
      'DeviceInfo:detail',
      'DeviceInfo:add',
      'DeviceInfo:delete',
      'DeviceInfo:edit',
      'SIMInfo:page',
      'SIMInfo:detail',
      'SIMInfo:add',
      'SIMInfo:delete',
      'SIMInfo:edit',
      'DeviceAlarmRecord:page',
      'DeviceAlarmRecord:detail',
      'DeviceAlarmRecord:add',
      'DeviceAlarmRecord:delete',
      'DeviceAlarmRecord:edit',
      'MileStatistics:page',
      'MileStatistics:detail',
      'MileStatistics:add',
      'MileStatistics:delete',
      'MileStatistics:edit',
      'DeviceAlarmStastic:page',
      'DeviceAlarmStastic:detail',
      'DeviceAlarmStastic:add',
      'DeviceAlarmStastic:delete',
      'DeviceAlarmStastic:edit',
      'FenceStatics:page',
      'FenceStatics:detail',
      'FenceStatics:add',
      'FenceStatics:delete',
      'FenceStatics:edit',
      'ContractList:page',
      'ContractList:detail',
      'ContractList:add',
      'ContractList:delete',
      'ContractList:edit',
      'OrderInfo:page',
      'OrderInfo:detail',
      'OrderInfo:add',
      'OrderInfo:delete',
      'OrderInfo:edit',
      'RentOrderInfo:page',
      'RentOrderInfo:detail',
      'RentOrderInfo:add',
      'RentOrderInfo:delete',
      'RentOrderInfo:edit',
      'ChangeBatteryRecord:page',
      'ChangeBatteryRecord:detail',
      'ChangeBatteryRecord:add',
      'ChangeBatteryRecord:delete',
      'ChangeBatteryRecord:edit',
      'ReturnList:page',
      'ReturnList:detail',
      'ReturnList:add',
      'ReturnList:delete',
      'ReturnList:edit',
      'DeviceInfo:transfer',
      'DeviceBattertCalib:page',
      'DeviceBattertCalib:detail',
      'DeviceBattertCalib:add',
      'DeviceBattertCalib:delete',
      'DeviceBattertCalib:edit',
      'DeviceInfo:dtree'
    ],
    'menus': [
      {
        'id': 142307070914633,
        'pid': 0,
        'name': 'sys_platform',
        'component': 'PageView',
        'redirect': null,
        'meta': {
          'title': '平台管理',
          'icon': 'safety-certificate',
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/platform',
        'hidden': false
      },
      {
        'id': 142307070914634,
        'pid': 142307070914633,
        'name': 'sys_app_mgr',
        'component': 'system/app/index',
        'redirect': null,
        'meta': {
          'title': '应用管理',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/app',
        'hidden': false
      },
      {
        'id': 142307070914642,
        'pid': 142307070914633,
        'name': 'sys_menu_mgr',
        'component': 'system/menu/index',
        'redirect': null,
        'meta': {
          'title': '菜单管理',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/menu',
        'hidden': false
      },
      {
        'id': 142307070914662,
        'pid': 0,
        'name': 'system_tools',
        'component': 'PageView',
        'redirect': null,
        'meta': {
          'title': '开发管理',
          'icon': 'euro',
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/tools',
        'hidden': false
      },
      {
        'id': 142307070914663,
        'pid': 142307070914662,
        'name': 'system_tools_config',
        'component': 'system/config/index',
        'redirect': null,
        'meta': {
          'title': '系统配置',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/config',
        'hidden': false
      },
      {
        'id': 142307070914671,
        'pid': 142307070914662,
        'name': 'sys_email_mgr',
        'component': 'system/email/index',
        'redirect': null,
        'meta': {
          'title': '邮件发送',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/email',
        'hidden': false
      },
      {
        'id': 142307070914674,
        'pid': 142307070914662,
        'name': 'sys_sms_mgr',
        'component': 'system/sms/index',
        'redirect': null,
        'meta': {
          'title': '短信管理',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/sms',
        'hidden': false
      },
      {
        'id': 142307070914678,
        'pid': 142307070914662,
        'name': 'sys_dict_mgr',
        'component': 'system/dict/index',
        'redirect': null,
        'meta': {
          'title': '字典管理',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/dict',
        'hidden': false
      },
      {
        'id': 142307070918731,
        'pid': 142307070914662,
        'name': 'sys_swagger_mgr',
        'component': 'Iframe',
        'redirect': null,
        'meta': {
          'title': '接口文档',
          'icon': null,
          'show': true,
          'target': '',
          'link': 'http://localhost:5566/'
        },
        'path': '/swagger',
        'hidden': false
      },
      {
        'id': 142307070918739,
        'pid': 0,
        'name': 'sys_monitor_mgr',
        'component': 'PageView',
        'redirect': null,
        'meta': {
          'title': '系统监控',
          'icon': 'deployment-unit',
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/monitor',
        'hidden': false
      },
      {
        'id': 142307070918740,
        'pid': 142307070918739,
        'name': 'sys_monitor_mgr_machine_monitor',
        'component': 'system/machine/index',
        'redirect': null,
        'meta': {
          'title': '服务监控',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/machine',
        'hidden': false
      },
      {
        'id': 142307070918742,
        'pid': 142307070918739,
        'name': 'sys_monitor_mgr_online_user',
        'component': 'system/onlineUser/index',
        'redirect': null,
        'meta': {
          'title': '在线用户',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/onlineUser',
        'hidden': false
      },
      {
        'id': 142307070918745,
        'pid': 142307070918739,
        'name': 'sys_monitor_mgr_druid',
        'component': 'Iframe',
        'redirect': null,
        'meta': {
          'title': '数据监控',
          'icon': null,
          'show': false,
          'target': '',
          'link': 'http://localhost:82/druid/login.html'
        },
        'path': '/druid',
        'hidden': false
      },
      {
        'id': 142307070918765,
        'pid': 0,
        'name': 'sys_timers',
        'component': 'PageView',
        'redirect': null,
        'meta': {
          'title': '任务调度',
          'icon': 'dashboard',
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/timers',
        'hidden': false
      },
      {
        'id': 142307070918766,
        'pid': 142307070918765,
        'name': 'sys_timers_mgr',
        'component': 'system/timers/index',
        'redirect': null,
        'meta': {
          'title': '任务管理',
          'icon': null,
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/timers',
        'hidden': false
      },
      {
        'id': 142307070918776,
        'pid': 0,
        'name': 'code_gen',
        'component': 'gen/codeGenerate/index',
        'redirect': null,
        'meta': {
          'title': '代码生成',
          'icon': 'thunderbolt',
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/codeGenerate/index',
        'hidden': false
      },
      {
        'id': 142307070922870,
        'pid': 0,
        'name': 'form_design',
        'component': 'system/formDesign/index',
        'redirect': null,
        'meta': {
          'title': '表单设计',
          'icon': 'robot',
          'show': true,
          'target': '',
          'link': null
        },
        'path': '/formDesign/index',
        'hidden': false
      }
    ],
    'dataScopes': [
      174827013677125,
      174827366686789,
      174829383766085,
      186755437695045,
      196888284803141,
      196964932288581,
      198054597918789,
      198067753734213,
      198237207265349,
      198249705594949,
      200153472262213,
      200154121171013,
      200658405277765
    ]
  },
  'extras': null,
  'timestamp': 1631366412272
}

export default dictData
